pipeline {
  agent any

  environment {
    // SonarQube server configured in Jenkins (Manage Jenkins > Configure System > SonarQube servers)
    SONAR_HOST_URL = "${SONAR_HOST_URL ?: 'http://sonarqube.local:9000'}"
    SONAR_LOGIN    = credentials('sonarqube-token') // credentials ID
  }

  stages {
    stage('Checkout') {
      steps {
        checkout([
          $class: 'GitSCM',
          branches: [[name: '*/master']],
          userRemoteConfigs: [[
            url: 'https://github.com/vinhle-dev/contact-manager.git',
          ]]
        ])
      }
    }

    /* stage('Build') {
      steps {
        script {
          bat 'npm install'
          bat 'npm run build'
        }
      }
    } */

    stage('SonarQube analysis') {
      /* environment {
        SCANNER_OPTS = '-Dsonar.sources=src -Dsonar.tests=src -Dsonar.sources.inclusions=**/*.ts -Dsonar.sources.exclusions=**/*.spec.ts -Dsonar.test.inclusions=**/*.spec.ts -Dsonar.projectKey=contact-manager -Dsonar.projectName=contact-manager'
      }
      steps {
        withSonarQubeEnv('MySonarQubeServer') {
          bat "sonar-scanner -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.login=${SONAR_LOGIN} ${SCANNER_OPTS}"
        }
      } */

      bat '''
      npm install -g @sonar/scan
      sonar \
        -Dsonar.host.url=http://localhost:9000 \
        -Dsonar.token=sqp_c85282d60c9157665b3156087009ba64536e48db \
        -Dsonar.projectKey=Contact-Manager
      '''
    }

    stage('Quality Gate') {
      steps {
        timeout(time: 5, unit: 'MINUTES') {
          waitForQualityGate abortPipeline: true
        }
      }
    }
  }

  post {
    always {
      echo "Pipeline done"
    }
    success {
      echo "Success: SonarQube scan passed."
    }
    failure {
      echo "Failure: check SonarQube and build logs."
    }
  }
}