pipeline {
  agent any
  environment {
    SONAR_PROJECT_KEY = 'Contact-Manager'
    SONAR_PROJECT_NAME = 'Contact Manager'
  }

  stages {
    stage('SonarQube analysis') {
      steps {
        withSonarQubeEnv('SonarQubeServer') {
          sh "sonar-scanner -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.projectName=${SONAR_PROJECT_NAME}"
        }
      }
    }

    /* stage('Quality Gate') {
      steps {
        script {
          timeout(time: 5, unit: 'MINUTES') {
            def qg = waitForQualityGate()
            if (qg.status != 'OK') {
              error "Pipeline aborted due to quality gate failure: ${qg.status}"
            }
          }
        }
      }
    } */
  }

  post {
    always {
      echo "Pipeline done"
    }
    success {
      echo "Success: SonarQube scan passed."
    }
    failure {
      echo "Failure: check SonarQube and build logs."
    }
  }
}